### PR TITLE
Inline docs & refactorings

### PR DESCRIPTION
**Pull request by juaristi**
One final thing that worries me is how to handle the un/signedness of read/fread return values.

### CODE REVIEW

**Comment by rockdaboot** [comment]
Cherry-picked 23fcb96 (the other commits are already in the 'wget2' branch).
Please remove your branch and start a new one from 'wget2' before you make any new changes.
Your branch is out-of-sync with 'wget2'.

**Comment by juaristi** [comment]
What happens with the signedness difference in read() and fread() return values?

**Comment by rockdaboot** [comment]
Well, we support just max 2GB long files :-) else reader() should return size_t.
Due to while(reader()>0) it seems ok to me. Error or end-of-file is detected.
Maybe a bit cleaner would be to check ferror() in __read() and return -1 on error.

**Comment by juaristi** [comment]
Yes, I guess it's cleaner. After the while loop we have
```
if (nbytes == -1 && errno != EAGAIN)
```
and since `fread()` returns 0 even in case of failure, it wouldn't enter the if, therefore not reporting the failure to the user. We check for the length later, but the user wouldn't know something bad happened, which is IMO something important.

Please check out this:
```
diff --git a/libwget/io.c b/libwget/io.c
index 679f800..41b92f4 100644
--- a/libwget/io.c
+++ b/libwget/io.c
@@ -54,7 +54,11 @@
 
 static ssize_t __read(const void *fp, char *dst, size_t len)
 {
-	return fread(dst, 1, len, (FILE *)fp);
+	FILE *f = (FILE *)fp;
+	size_t ret = fread(dst, 1, len, f);
+	if (ferror(f))
+		return -1;
+	return ret;
 }
 
 static ssize_t __readfd(const void *f, char *dst, size_t len)
-- 
```
I don't know why, but when I preview this message GitHub converts tabs to spaces, please take it into account when merging.

**Comment by rockdaboot** [comment]
Thanks, slightly amended and pushed

**Pull request closed without merging**
