### PR TITLE
wget: new option --follow-metalink

### PR DESCRIPTION
**Pull request by giuseppe**
* src/options.h (struct config): Define follow_metalink.
* src/options.c (print_help): Add description for follow-metalink.
(struct options): Add follow-metalink.
(struct config): Initialize follow_metalink.
* src/wget.c (downloader_thread): Skip following metalinks when follow_metalink is off.
(_get_header): Store the metalink file when follow_metalink is false.

### CODE REVIEW

**Comment by rockdaboot** [comment]
Very good ! I'll merge it when back on the desktop. Wdyt about enabling it with --mirror ?

**Comment by giuseppe** [comment]
good idea.  I amended it in the new version

**Comment by rockdaboot** [comment]
WDYT about renaming --follow-metalink into --metalink ?
Also, we need a --force-metalink <file>. Do you plan such a thing or should I add it ?

**Comment by giuseppe** [comment]
I am fine with renaming it.  What would --force-metalink do?  How will it be different than --input-metalink?

**Comment by rockdaboot** [comment]
`--input-metalink` is IMO badly named (it is currently wget1.x only).
The way wget1/2 specifies file types is via --force-<type> --input-file <file>.
To be consistent, we should have --force-metalink and not --input-metalink <file>.

On the other hand side, we could obsolete the combination of --force-<type> and --input-file and replace it by --input-<type>. Less to type, easier to read and memorize. And makes it possible to specify multiple files with different types on one command line.

**Comment by rockdaboot** [comment]
Meanwhile I added --force-metalink and made some metalink code cleanups.

**Pull request merged**
