### PR TITLE
Support for HTML CSS style tag and attr + fix for page-requisites

### PR DESCRIPTION
**Pull request by MichaelHeerklotz**
Support for HTML CSS style tag and attr
-> should now be clean and working code
-> test added for this feature

fix for page-requisites
-> cleans up the code, the old code already downloads any link href ignoring the rel value, the "fix" just cleans the code for this behavior
see https://github.com/rockdaboot/wget2/issues/183

### CODE REVIEW

**Comment by rootkea** [comment]
@MichaelHeerklotz Nice work!
You might want to look at how to auto-close an issue with a PR https://github.com/blog/1506-closing-issues-via-pull-requests :)

**Comment by rockdaboot** [comment]
Awesome work !
I rebased your branch onto master and made some small amendments, pushed it to branch 'html_style' here. I didn't have time to fix the commit message yet - I'll do it tomorrow... Thank you very much for this contribution !

**Comment by MichaelHeerklotz** [comment]
Thank you.
Very nice work with the "page-requisites" fix/update! I would not have thought, that it is possible with so few changes.

**Comment by rockdaboot** [comment]
Pushed manually, thanks for contribution !

**Pull request closed without merging**
