### PR TITLE
Use gnulib human readable

### PR DESCRIPTION
**Pull request by darnir**
I would like to merge these two commits as well. They get rid of the wget_human_readable function and instead use the one provided by gnulib.

### CODE REVIEW

**Comment by rockdaboot** [comment]
Nice. I didn't know that there is such a function within gnulib.
I would like to merge all your commits tomorrow... is that ok ?

**Comment by rockdaboot** [comment]
Any idea why Travis is mourning ?

**Comment by darnir** [comment]
I think I'm fine with the merging.
There is one problem I can currently see, I'll create a new issue for it.

About Travis complaining, I have absolutely no idea. Was hoping you knew more. From a brief glimpse at the logs, it is complaining because of too many errors. The errors all seem to stem from a shadow declaration of the options struct. But I'm not sure how that happens only on Mac and only after my changes. These changes don't affect anything in that area, and the progress bar commits all built fine in #96 .

**Comment by darnir** [comment]
The solaris buildbots are complaining about the same error as Travis on Mac. We really should check this out.

**Comment by rockdaboot** [comment]
Your renaming is no explanation... I'll check on Solaris and report back.

**Comment by rockdaboot** [comment]
It is gnulib 'human' modul that pulls in module 'unistd' which in turn includes the gnulib variant 'getopt.h' via 'unistd.h' - so renaming is a good idea, but maybe we we don't use wget_ as prefix. That is the namespace of libwget, we shouldn't mix that. How do you like 'optionx', 'optionw' or 'woption' ?

Also, we should include the 'unistd' module in bootstrap.conf.

**Comment by darnir** [comment]
Yes, I agree that we should not use `wget_` due to namespace conflicts. This was a test I ran yesterday after looking at the build logs. `optionw` seems like an okay name to me.

What I can't understand is why the human module pulls in these dependencies only on OSX and Solaris. Also, if it does, it should be listed in the modules file, I don't see it there.

**Comment by rockdaboot** [comment]
There is ABOUT-NLS in your commit (that is an auto-generated file).
Where do these changes in po/.gitignore come from ?

**Comment by darnir** [comment]
Aah, those seem to have automatically propped up after I ran a `make maintainer-clean` and rebuilt everything.

**Comment by darnir** [comment]
I have removed the changes from the gitignore files. I don't know where they came from.

**Comment by rockdaboot** [comment]
I just pushed your commits to master. Good work !

**Pull request closed without merging**
