### PR TITLE
* Makefile.am: Add targets for checking code coverage

### PR DESCRIPTION
**Pull request by darnir**

### CODE REVIEW

**Comment by rockdaboot** [comment]
Code coverage / lcov is so cool ! I never really used it before (just read about it)... and it is such a gain.

**Comment by darnir** [comment]
It is! I set it up long ago for Wget 1.x, but never got anywhere with it. Here, I think we can use this to improve our test coverage and eliminate unneeded functions

**Comment by rockdaboot** [comment]
First thing I saw was 0% test coverage for CSS 😨

**Comment by darnir** [comment]
That and http_highlevel.c surprised me as well. We need quite a few more tests

**Comment by rockdaboot** [comment]
Http_highlevel  ist currently used in examples/ . At some point I would like to run the examples as tests or at least test them somehow.

**Pull request merged**
