### PR TITLE
Retain a copy of download context for progress bar

### PR DESCRIPTION
**Pull request by darnir**
When the screen is scrolled or resized, we often need to redraw the
entire progress bar. However, when some threads have completed
downloading, this can cause those progress slots to become blank since
their contexts were deleted and hence lost. To prevent this, keep a copy
of the last context in the slot, so we can access it later for printing
the progress bar.

* libwget/bar.c (_bar_slot_t): New member, last_ctx
  (wget_bar_deregister): Create a copy of the context just before we
  deregister. This ensures that we copy the latest data for printing
  (wget_bar_update): If no context is registered, then try printing the
  last context available
  (_bar_print_final): Make the method signature similar to
  wget_bar_update for consistency

### CODE REVIEW

**Comment by rockdaboot** [comment]
Could you correct the spelling in the last line and then it is fine.

**Comment by darnir** [comment]
Done

**Comment by darnir** [comment]
Where would you like it? Currently it's already printed at the end of the  progress bar.

**Comment by rockdaboot** [comment]
Total # of Bytes in the bottom line. It always shows Bytes: 0 here.

**Comment by darnir** [comment]
That happens because the value of quota isn't being correctly updated. This is because all calls to `quota_modify_read()` use the expression `(config.save_headers ? resp->header->length : 0)`. Since, the --save-headers option isn't passed to Wget, the calls to update quota all add 0 bytes, hence causing the 0 bytes Downloaded in the display as well.

This also implies that we have a bug in the quota compuation

**Comment by darnir** [comment]
This closes #99

**Comment by rockdaboot** [comment]
Good thought, quota fixed in master.

**Pull request closed without merging**
