### PR TITLE
Use bootstrap

### PR DESCRIPTION
**Pull request by juaristi**
As per the discussion in #76.

It tries to download .po files from translationproject.org, but it fails (are we using it?). So we have to pass `--skip-po`. Also, I've taken the following versions from wget's `bootstrap.conf`:

- autoconf: 2.62
- automake: 1.11.1
- git: 1.4.4

Tell me if there's something missing.

### CODE REVIEW

**Comment by juaristi** [comment]
I've deliberately set `use_libtool=1`, because `autogen.sh` passes the `--libtool` option to `gnulib-tool`.

**Comment by rockdaboot** [comment]
Merging your changes here results in
```
$ ./bootstrap                                                                                                  
./bootstrap: Bootstrapping from checked-out wget2 sources...
./bootstrap: consider installing git-merge-changelog from gnulib
./bootstrap: getting gnulib files...
fatal: Not a git repository: ../.git/modules/gnulib
Unable to find current revision in submodule path 'gnulib'
```

**Comment by rockdaboot** [comment]
Sorry, forget it. Retrying with a freshly cloned repo from Savannah worked !

**Comment by rockdaboot** [comment]
Please add SKIP_PO=1 to bootstrap.conf, so we don't need to use --skip-po option.
Also, please remove autogen.sh and amend all files that refer to it:
- README.md
- contrib/check-hard
- contrib/mingw
- docs/mainpage.md
- .travis.sh

**Comment by rockdaboot** [comment]
@juaristi Kindly reminder :-)

**Comment by juaristi** [comment]
Please, have a look at it.
I've replaced `autogen.sh` invocations by `bootstrap` ones, since I believe it's a replacement for it. Tell me if there's something I missed.

**Pull request closed without merging**
